name: cafeteria_inventario
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.2+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_core: ^4.2.0
  intl: ^0.20.2
  fl_chart: ^1.1.1
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  dio: ^5.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_filex: ^4.5.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # --- ¡AQUÍ ESTABA EL ERROR! ---
  # Ahora está alineado a la izquierda, al mismo nivel que flutter_test
  flutter_launcher_icons: "^0.13.1"
  # ------------------------------

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_cafeteria.png

# Configuración de los Iconos (Esto está perfecto al final)
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_cafeteria.png"
  min_sdk_android: 21